#!/bin/bash
today=`date '+%Y_%m_%d__%H_%M_%S'`;

function validate () {
    if [ $? -ne 0 ]; then
        echo "Tests failed :(";
        exit 1;
    fi
}

make
validate

sudo make install
validate

#mm-webrecord ~/tmp_liz/diy_$today 
validate

python sample_cloud_apps/invoke_lambda.py
validate
python sample_cloud_apps/invoke_lambda.py
python sample_cloud_apps/invoke_lambda.py
echo "Tests passed :-)"
